basePath: /
host: localhost:5000
info:
  contact: {}
  description: Backend for the aggregate-site project
  license:
    name: MIT
  title: aggregate-site-backend
  version: "1.0"
paths:
  /query:
    get:
      description: Consume lat, long, and current params, and return a list of events
        that are separated by categories
      parameters:
      - description: latitude of the place
        format: float64
        in: query
        name: lat
        required: true
        type: number
      - description: longitude of the place
        format: float64
        in: query
        name: long
        required: true
        type: number
      - description: 1 for present, 0 for past, any for all
        in: query
        name: current
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Query the backend for relevant events surrounding a coordinate
      tags:
      - query
swagger: "2.0"
